### ISSUE TITLE
checkout page does not play well with Plone's login modal

### ISSUE THREAD

**Issue by cewing** [jazkarta/jazkarta.shop#26] opened 2016-08-05 17:53 UTC
The Plone login modal is intended to close when login is complete and reload the parent page.  The checkout view of this product does not do so.  When login is completed, the entire checkout page is rendered in the login form, and the modal does not close of its own accord.
### To Reproduce:
- install the `jazkarta.shop` package in a fresh Plone site and configure it
- put an item in your cart
- click the 'checkout' button in the cart to proceed to the `review-cart` view
- review the cart and click "proceed to checkout" to get to the `checkout` view
- click login to open the login modal and fill out and submit the login form in that modal

(you can also proceed to check out successfully so that you are viewing the thank you page at the end of the process)
#### Expected Result

The login form modal should close and the checkout form should reload in an authenticated state. 
#### Actual Result

Instead, the modal remains open and the checkout page is rendered, with an empty address form, into the modal.

**Comment by cewing** [comment] 2016-08-05 17:53
see also jazkarta/sdhsp-buildout#23

**Comment by witekdev** [comment] 2022-03-25 08:14
This issue still exists, can be seen on SD project. Navigate yourself to checkout view as anon, login via link. See the checkout contents rendered inside a modal

**Comment by alecpm** [comment] 2022-04-04 16:59
@witekdev Could you provide a bit more detail on how to reproduce this? When I take the following steps

* Visit https://www.sdhspress.com/books/a-place-for-harvest as anon
* Click "Add to cart"
* Click cart icon in upper right and click "Checkout" button
* Click the login link on the upper right to open a login modal
* Login

I get redirected to the checkout page with no modal.

**Comment by alecpm** [comment] 2022-04-04 17:29
Nevermind, I see it. It doesn't happen from the cart or shipping pages, only from the final checkout page. It seems very strange to me that this only happens from the final checkout page and not any other pages (including the similar shipping page), especially since there doesn't seem to be any special modal customizations made on that page. The modal behavior is determined by the the modal `pattern-options` which are set site wide to `{"actionOptions": {"displayInModal": false}}`, and are set on the login link to `{"prependContent": ".portalMessage", "title": "Log in", "width": "26em"}`.

I just can't understand why the login link on `/checkout` is behaving differently from on every other page. The `displayInModal: false` setting seems intended to prevent this, but it's not triggering on that page for some reason.

An alternative would be if the login link included pattern options like `{"actionOptions": {"redirectOnResponse": true}}` or `{"actionOptions": {"disableAjaxFormSubmit": true}}`.

**Comment by alecpm** [comment] 2022-04-04 17:40
I see what's happening. The checkout page always includes the following HTML:

```
<div class="portalMessage error checkout-error-wrapper" style="display: none;">
      <strong>Error</strong>
      <span class="checkout-error"></span>
</div>
```

The AJAX form machinery looks explicitly for `".portalMessage.error, .alert-danger"` in the form response and treats the presence of a matching element as a form submission error which it loads in the modal.

We should probably either use a custom set of classes for the checkout JS error handling or only add the `error` class to the message element when an error is detected before showing the element.

**Comment by alecpm** [comment] 2022-04-06 20:45
This is fixed on master by using class `alert-error` rather than `error` which provides the same styling without the automated modal hijacking behavior.

**Closed as completed** 2022-04-06 20:45 UTC
Labels: bug, UI / UX
